USE QLTB
create table NHAN_HIEU (
 MA_NSX VARCHAR(10) PRIMARY KEY,
 TEN_NSX NVARCHAR(100) NOT NULL,
 NUOC NVARCHAR(100) NOT NULL,
);

CREATE TABLE LOAI_TB (
 MA_LOAI VARCHAR(10) PRIMARY KEY,
 TEN_LOAI NVARCHAR(100) NOT NULL UNIQUE,
);

CREATE TABLE DON_VI(
 MA_DV VARCHAR(10) PRIMARY KEY,
 TEN_DV NVARCHAR(100) NOT NULL UNIQUE,
);

CREATE TABLE PHONG(
 MA_PHONG VARCHAR(10) PRIMARY KEY,
 VI_TRI NVARCHAR(100) NOT NULL UNIQUE,
 DIEN_TICH FLOAT CHECK (DIEN_TICH > 0),
);

CREATE TABLE PHG_DV (
    MA_PHONG VARCHAR(10),
    MA_DV VARCHAR(10),
    NGAY_BD DATE NOT NULL,
    NGAY_KT DATE,

    PRIMARY KEY (MA_PHONG, MA_DV, NGAY_BD),
    CHECK (NGAY_KT IS NULL OR NGAY_KT >= NGAY_BD),

    FOREIGN KEY (MA_PHONG) REFERENCES PHONG(MA_PHONG)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    FOREIGN KEY (MA_DV) REFERENCES DON_VI(MA_DV)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


CREATE TABLE THIET_BI(
 MA_TB VARCHAR(10) PRIMARY KEY,
 TEN_TB NVARCHAR(50) NOT NULL,
 MA_NHHIEU VARCHAR(10) NOT NULL,
 MODEL NVARCHAR(50) NOT NULL,
 NAM_SX INT CHECK (NAM_SX > 2000),
 MA_LOAI VARCHAR(10) NOT NULL,
 FOREIGN KEY (MA_LOAI) REFERENCES LOAI_TB(MA_LOAI)
  ON UPDATE CASCADE
  ON DELETE NO ACTION
);

CREATE TABLE NV(
 MA_NV VARCHAR(10) PRIMARY KEY CHECK (MA_NV LIKE '[A-Z][1-9][0-9][0-9][0-9][0-9][0-9]'),
 HO_NV NVARCHAR(10) NOT NULL UNIQUE,
 TEN_NV NVARCHAR(50),
 PHAI NVARCHAR(10) NOT NULL CHECK (PHAI IN (N'Nam', N'Nữ', N'Khác')),
 NGAY_BD_CTAC DATE NOT NULL,
);

CREATE TABLE MON_TB(
 MA_MON VARCHAR(10) PRIMARY KEY,
 MA_TB VARCHAR(10) NOT NULL,
 NGAY_MUA DATE NOT NULL,
 TRI_GIA_MUA DECIMAL(16,2) CHECK (TRI_GIA_MUA > 0), 
 FOREIGN KEY (MA_TB) REFERENCES THIET_BI(MA_TB)
  ON UPDATE CASCADE
  ON DELETE NO ACTION
);

CREATE TABLE LDAO_CQ(
 MA_NV VARCHAR(10) NOT NULL,
 CHUC_VU NVARCHAR(50) NOT NULL,
 NGAY_BD DATE NOT NULL,
 NGAY_KT DATE,
 PRIMARY KEY (MA_NV, NGAY_BD),
 CHECK (NGAY_KT IS NULL OR NGAY_KT >= NGAY_BD),
 FOREIGN KEY (MA_NV) REFERENCES NV(MA_NV)
  ON UPDATE CASCADE
  ON DELETE CASCADE
);

CREATE TABLE LDAO_DV(
 MA_NV VARCHAR(10),
 MA_DV VARCHAR(10),
 CHUC_VU NVARCHAR(50) NOT NULL,
 NGAY_BD DATE NOT NULL,
 NGAY_KT DATE,

 PRIMARY KEY (MA_NV, MA_DV, NGAY_BD),
 CHECK (NGAY_KT IS NULL OR NGAY_KT >= NGAY_BD),

 FOREIGN KEY (MA_NV) REFERENCES NV(MA_NV)
 ON UPDATE CASCADE
 ON DELETE CASCADE,

 FOREIGN KEY (MA_DV) REFERENCES DON_VI(MA_DV)
 ON UPDATE CASCADE
 ON DELETE CASCADE
 );

 CREATE TABLE PHTRACH_TB(
	MA_NV VARCHAR(10),
	MA_DV VARCHAR(10),
	NGAY_BD DATE NOT NULL,
    NGAY_KT DATE,

	PRIMARY KEY (MA_NV, MA_DV, NGAY_BD),
    CHECK (NGAY_KT IS NULL OR NGAY_KT >= NGAY_BD),

	FOREIGN KEY (MA_NV) REFERENCES NV(MA_NV)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    FOREIGN KEY (MA_DV) REFERENCES DON_VI(MA_DV)
        ON UPDATE CASCADE
        ON DELETE CASCADE
 );

CREATE TABLE PH_PHOI_TB (
    MA_PHONG VARCHAR(10),
    MA_MON VARCHAR(10),
    NGAY_BD DATE NOT NULL,
    NGAY_KT DATE,
    MUC_TTRANG VARCHAR(50)
        CHECK (MUC_TTRANG IN ('Tốt','Hỏng','Bảo trì','Thanh lý')),
    MO_TA_TTRANG VARCHAR(255),

    PRIMARY KEY (MA_PHONG, MA_MON, NGAY_BD),
    CHECK (NGAY_KT IS NULL OR NGAY_KT >= NGAY_BD),

    FOREIGN KEY (MA_PHONG) REFERENCES PHONG(MA_PHONG)
        ON UPDATE CASCADE
        ON DELETE NO ACTION,

    FOREIGN KEY (MA_MON) REFERENCES MON_TB(MA_MON)
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);

CREATE TABLE THANH_LY (
    MA_MON VARCHAR(10),
    NGAY_GIO DATETIME,
    TRI_GIA DECIMAL(15,2) NOT NULL CHECK (TRI_GIA > 0),
    DV_TIEN VARCHAR(10) NOT NULL,

    PRIMARY KEY (MA_MON, NGAY_GIO),

    FOREIGN KEY (MA_MON) REFERENCES MON_TB(MA_MON)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


CREATE TABLE KHAU_HAO (
    MA_MON VARCHAR(10),
    NGAY DATE,
    TY_LE_KH FLOAT NOT NULL CHECK (TY_LE_KH >= 0 AND TY_LE_KH <= 1),

    PRIMARY KEY (MA_MON, NGAY),

    FOREIGN KEY (MA_MON) REFERENCES MON_TB(MA_MON)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
INSERT INTO LOAI_TB(MA_LOAI,TEN_LOAI)
VALUES ('MHBPA26',
		N'MÁY HÚT BỤI'
		)
INSERT INTO THIET_BI(MA_TB,TEN_TB,MA_NHHIEU,MODEL,NAM_SX,MA_LOAI)
VALUES ('TB 10',
		N'MÁY HÚT BỤI PANASONIC',
		'PANASONIC',
		N'NEW',
		'20260206',
		'MHBPA26'
		)
DELETE FROM THIET_BI
WHERE MA_LOAI = 'TLPA26'

DELETE FROM LOAI_TB
WHERE MA_LOAI = 'TLPA26'

SELECT *FROM LOAI_TB
SELECT *FROM THIET_BI

SELECT MA_TB,TEN_TB
FROM THIET_BI
WHERE MA_NHHIEU = 'PANASONIC'